<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeInputStreamAsFile</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaW5QaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpJbnB1
dFN0cmVhbSBpbnB1dFN0cmVhbSA9IChJbnB1dFN0cmVhbSkgSURhdGFVdGlsLmdldChpblBpcGVs
aW5lQ3Vyc29yLCAiaW5wdXRTdHJlYW0iKTsKU3RyaW5nIGluRmlsZURpcmVjdG9yeSA9IChTdHJp
bmcpIElEYXRhVXRpbC5nZXQoaW5QaXBlbGluZUN1cnNvciwgImluRmlsZURpcmVjdG9yeSIpOwpT
dHJpbmcgaW5GaWxlbmFtZSA9IChTdHJpbmcpIElEYXRhVXRpbC5nZXQoaW5QaXBlbGluZUN1cnNv
ciwgImluRmlsZW5hbWUiKTsKaW5QaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgpTdHJpbmcgb3V0
RmlsZVBhdGggPSBpbkZpbGVEaXJlY3RvcnkraW5GaWxlbmFtZTsKCnRyeSB7CglGaWxlIHRhcmdl
dERpcmVjdG9yeSA9IG5ldyBGaWxlKGluRmlsZURpcmVjdG9yeSk7CglpZighdGFyZ2V0RGlyZWN0
b3J5LmV4aXN0cygpKSB7CgkJdGFyZ2V0RGlyZWN0b3J5Lm1rZGlycygpOwoJfQoJRmlsZXMuY29w
eShpbnB1dFN0cmVhbSwgUGF0aHMuZ2V0KG91dEZpbGVQYXRoKSwgU3RhbmRhcmRDb3B5T3B0aW9u
LlJFUExBQ0VfRVhJU1RJTkcpOwp9IGNhdGNoKElPRXhjZXB0aW9uIGlvZSkgewoJdGhyb3cgbmV3
IFNlcnZpY2VFeGNlcHRpb24oaW9lKTsKfSBmaW5hbGx5IHsKCXRyeSB7CgkJaW5wdXRTdHJlYW0u
Y2xvc2UoKTsKCX0gY2F0Y2goSU9FeGNlcHRpb24gaW9lKSB7CgkJCgl9CQkJCn0KCklEYXRhQ3Vy
c29yIG91dFBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhVXRpbC5w
dXQob3V0UGlwZWxpbmVDdXJzb3IsICJvdXRGaWxlUGF0aCIsIG91dEZpbGVQYXRoKTsKb3V0UGlw
ZWxpbmVDdXJzb3IuZGVzdHJveSgpOwo=</value>
</Values>
